language: julia
sudo: required
dist: trusty
os:
  - linux
julia:
  - 1.0
addons:
  apt:
    packages:
      - expect-dev # for unbuffer
matrix:
  include:
  - name: "Unit Tests"
    env: TEST_SUITE=unit
notifications:
  email: false
script:
  - export JL_PKG=NonlinearEigenproblems
  - unbuffer git fetch --unshallow
  - unbuffer julia --color=yes -e "using Pkg; Pkg.build()"
  - #if [ $TEST_SUITE = 'unit' ]; then julia --check-bounds=yes --color=yes -e 'using Pkg; Pkg.test(coverage=true)'; fi
  - #if [ $TEST_SUITE = 'benchmark' ]; then julia -O3 --color=yes test/benchmark/run_benchmark.jl benchmark.json 1.0; fi
after_success:
  - #if [ $TEST_SUITE = 'unit' ]; then julia -e 'using Pkg; Pkg.add("Coverage"); include("test/submit_test_coverage.jl")'; fi
  - #if [ $TEST_SUITE = 'benchmark' ]; then ./scripts/submit_benchmark.sh; fi
