language: julia
sudo: required
dist: trusty
os:
  - linux
julia:
  - 1.0
addons:
  apt:
    packages:
      - expect-dev # for unbuffer
matrix:
  include:
  - name: "Unit Tests"
    env: TEST_SUITE=unit
  - name: "Benchmarks"
    env: TEST_SUITE=benchmark
notifications:
  email: false
script:
  - unbuffer git fetch --unshallow
  - unbuffer julia --color=yes -e 'using Pkg; Pkg.activate("."); Pkg.build()'
  - unbuffer julia --color=yes -e 'using Pkg; Pkg.activate("test"); Pkg.build()'
  - if [ $TEST_SUITE = 'unit' ]; then unbuffer julia --color=yes --code-coverage --check-bounds=yes -e 'using Pkg; Pkg.activate("test"); include("test/runtests.jl")'; fi
  - if [ $TEST_SUITE = 'benchmark' ]; then unbuffer julia -O3 --color=yes -e 'using Pkg; Pkg.activate("test"); include("test/benchmark/run_benchmark.jl")' benchmark.json 1.0; fi
after_success:
  - if [ $TEST_SUITE = 'unit' ]; then unbuffer julia -e 'using Pkg; Pkg.add("Coverage"); include("test/submit_test_coverage.jl")'; fi
  - if [ $TEST_SUITE = 'benchmark' ]; then unbuffer ./scripts/submit_benchmark.sh; fi
