language: julia
sudo: required
dist: trusty
os:
  - linux
julia:
  - 1.0
matrix:
  include:
  - name: "Benchmarks"
    env: TEST_SUITE=benchmark
notifications:
  email: false
script:
  - export JL_PKG=NonlinearEigenproblems
  - git fetch --unshallow
  - julia --color=yes -e "using Pkg; Pkg.build()"
  - if [ $TEST_SUITE = 'unit' ]; then julia --check-bounds=yes --color=yes -e 'using Pkg; Pkg.test(coverage=true)'; fi
  - if [ $TEST_SUITE = 'benchmark' ]; then julia -O3 --color=yes test/run_benchmark.jl benchmark.json 1.0; fi
after_success:
  - branch=`git symbolic-ref --short HEAD`
  - commit=`git rev-parse --short HEAD`
  - benchmark_file_name=benchmark-$branch-$TRAVIS_BUILD_NUMBER-$commit.json
  - git clone --depth=10 --branch=master https://github.com/maxbennedich/julia-ci.git julia-ci-benchmark
  - mv benchmark.json julia-ci-benchmark/$benchmark_file_name
  - cd julia-ci-benchmark
  - git config user.email benchmark
  - git config user.name benchmark
  - git add $benchmark_file_name
  - git commit -m "benchmark $commit"
  - git push "https://$GIT_TOKEN@github.com/maxbennedich/julia-ci.git" master > /dev/null 2>&1
