language: julia
sudo: required
dist: trusty
os:
  - linux
julia:
  - 0.7
notifications:
  email: false
#script:
#  - git fetch --unshallow
#  - julia --color=yes -e 'using Pkg; Pkg.build()'
#  - julia --check-bounds=yes --color=yes -e 'Pkg.test("NonlinearEigenproblems", coverage=true)'
after_success:
  - julia -e 'Pkg.add("Coverage"); include("test/submit_test_coverage.jl")'
