language: julia
os:
  - linux
julia:
  - 0.6
cache:
  directories:
  # cache all packages
  - $HOME/.julia/v0.6
before_cache:
  # ...except our own package
  - rm -rf $HOME/.julia/v0.6/NonlinearEigenproblems
script:
  - rm -rf $HOME/.julia/v0.6/HDF5
  - git fetch --unshallow
  - julia --color=yes -e 'Pkg.clone(pwd())'
  - julia --color=yes -e 'Pkg.build("NonlinearEigenproblems")'
  - julia --check-bounds=yes --color=yes -e 'Pkg.test("NonlinearEigenproblems", coverage=true)'
