language: julia
sudo: required
dist: trusty
os:
  - linux
julia:
  - 0.7
notifications:
  email: false
script:
  - export JL_PKG=NonlinearEigenproblems
  - git fetch --unshallow
  - julia --color=yes -e "if VERSION < v\"0.7.0-DEV.5183\"; Pkg.clone(pwd()); Pkg.build(\"${JL_PKG}\"); else using Pkg; Pkg.build(); end"
  - julia --check-bounds=yes --inline=no --color=yes -e "if VERSION < v\"0.7.0-DEV.5183\"; Pkg.test(\"${JL_PKG}\", coverage=true); else using Pkg; Pkg.test(coverage=true); end"
after_success:
  - julia -e 'Pkg.add("Coverage"); include("test/submit_test_coverage.jl")'
