language: julia
sudo: required
dist: trusty
os:
  - linux
julia:
  - 1.0
matrix:
  include:
  - name: "Unit Tests"
    env: TEST_SUITE=unit
  - name: "Benchmarks"
    env: TEST_SUITE=benchmark
notifications:
  email: false
script:
  - export JL_PKG=NonlinearEigenproblems
  - git fetch --unshallow
  - julia --color=yes -e "using Pkg; Pkg.build()"
  - julia --check-bounds=yes --color=yes -e "using Pkg; Pkg.test(coverage=true)"
after_success:
  - if [ $TEST_SUITE = 'unit' ]; then julia -e 'using Pkg; Pkg.add("Coverage"); include("test/submit_test_coverage.jl")'; fi
